/* eslint-disable prettier/prettier */
export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_STARTED = 'SIGNUP_STARTED';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const GETPROFILE_STARTED = 'GETPROFILE_STARTED';
export const GETPROFILE_REQUEST = 'GETPROFILE_REQUEST';
export const GETPROFILE_SUCCESS = 'GETPROFILE_SUCCESS';
export const GETPROFILE_FAILURE = 'GETPROFILE_FAILURE';

export const GETBROADCASTMESSAGES_STARTED = 'GETBROADCASTMESSAGES_STARTED';
export const GETBROADCASTMESSAGES_REQUEST = 'GETBROADCASTMESSAGES_REQUEST';
export const GETBROADCASTMESSAGES_SUCCESS = 'GETBROADCASTMESSAGES_SUCCESS';
export const GETBROADCASTMESSAGES_FAILURE = 'GETBROADCASTMESSAGES_FAILURE';

export const GETCONTACTS_STARTED = 'GETCONTACTS_STARTED';
export const GETCONTACTS_REQUEST = 'GETCONTACTS_REQUEST';
export const GETCONTACTS_SUCCESS = 'GETCONTACTS_SUCCESS';
export const GETCONTACTS_FAILURE = 'GETCONTACTS_FAILURE';

export const UPDATEPROFILE_STARTED = 'UPDATEPROFILE_STARTED';
export const UPDATEPROFILE_REQUEST = 'UPDATEPROFILE_REQUEST';
export const UPDATEPROFILE_SUCCESS = 'UPDATEPROFILE_SUCCESS';
export const UPDATEPROFILE_FAILURE = 'UPDATEPROFILE_FAILURE';

export const ADDFAVOURITE_STARTED = 'ADDFAVOURITE_STARTED';
export const ADDFAVOURITE_REQUEST = 'ADDFAVOURITE_REQUEST';
export const ADDFAVOURITE_SUCCESS = 'ADDFAVOURITE_SUCCESS';
export const ADDFAVOURITE_FAILURE = 'ADDFAVOURITE_FAILURE';

export const RECENTCONTACT_STARTED = 'RECENTCONTACT_STARTED';
export const RECENTCONTACT_REQUEST = 'RECENTCONTACT_REQUEST';
export const RECENTCONTACT_SUCCESS = 'RECENTCONTACT_SUCCESS';
export const RECENTCONTACT_FAILURE = 'RECENTCONTACT_FAILURE';

export const ACHIEVEMENTS_STARTED = 'ACHIEVEMENTS_STARTED';
export const ACHIEVEMENTS_REQUEST = 'ACHIEVEMENTS_REQUEST';
export const ACHIEVEMENTS_SUCCESS = 'ACHIEVEMENTS_SUCCESS';
export const ACHIEVEMENTS_FAILURE = 'ACHIEVEMENTS_FAILURE';

export const MYGAMES_STARTED = 'MYGAMES_STARTED';
export const MYGAMES_REQUEST = 'MYGAMES_REQUEST';
export const MYGAMES_SUCCESS = 'MYGAMES_SUCCESS';
export const MYGAMES_FAILURE = 'MYGAMES_FAILURE';

export const CREATEWORKINGDEAL_STARTED = 'CREATEWORKINGDEAL_STARTED';
export const CREATEWORKINGDEAL_REQUEST = 'CREATEWORKINGDEAL_REQUEST';
export const CREATEWORKINGDEAL_SUCCESS = 'CREATEWORKINGDEAL_SUCCESS';
export const CREATEWORKINGDEAL_FAILURE = 'CREATEWORKINGDEAL_FAILURE';

export const WORKINGDEALLIST_STARTED = 'WORKINGDEALLIST_STARTED';
export const WORKINGDEALLIST_REQUEST = 'WORKINGDEALLIST_REQUEST';
export const WORKINGDEALLIST_SUCCESS = 'WORKINGDEALLIST_SUCCESS';
export const WORKINGDEALLIST_FAILURE = 'WORKINGDEALLIST_FAILURE';


export const WORKINGDEALUPDATE_STARTED = 'WORKINGDEALUPDATE_STARTED';
export const WORKINGDEALUPDATE_REQUEST = 'WORKINGDEALUPDATE_REQUEST';
export const WORKINGDEALUPDATE_SUCCESS = 'WORKINGDEALUPDATE_SUCCESS';
export const WORKINGDEALUPDATE_FAILURE = 'WORKINGDEALUPDATE_FAILURE';

export const WORKINGDEALDELETE_STARTED = 'WORKINGDEALDELETE_STARTED';
export const WORKINGDEALDELETE_REQUEST = 'WORKINGDEALDELETE_REQUEST';
export const WORKINGDEALDELETE_SUCCESS = 'WORKINGDEALDELETE_SUCCESS';
export const WORKINGDEALDELETE_FAILURE = 'WORKINGDEALDELETE_FAILURE';

export const TERMSCONDITION_STARTED = 'TERMSCONDITION_STARTED';
export const TERMSCONDITION_REQUEST = 'TERMSCONDITION_REQUEST';
export const TERMSCONDITION_SUCCESS = 'TERMSCONDITION_SUCCESS';
export const TERMSCONDITION_FAILURE = 'TERMSCONDITION_FAILURE';

export const MTDBOOKINGDETAILS_STARTED = 'MTDBOOKINGDETAILS_STARTED';
export const MTDBOOKINGDETAILS_REQUEST = 'MTDBOOKINGDETAILS_REQUEST';
export const MTDBOOKINGDETAILS_SUCCESS = 'MTDBOOKINGDETAILS_SUCCESS';
export const MTDBOOKINGDETAILS_FAILURE = 'MTDBOOKINGDETAILS_FAILURE';


export const MTDTOTAL_STARTED = 'MTDTOTAL_STARTED';
export const MTDTOTAL_REQUEST = 'MTDTOTAL_REQUEST';
export const MTDTOTAL_SUCCESS = 'MTDTOTAL_SUCCESS';
export const MTDTOTAL_FAILURE = 'MTDTOTAL_FAILURE';

export const MTDBOOKED_STARTED = 'MTDBOOKED_STARTED';
export const MTDBOOKED_REQUEST = 'MTDBOOKED_REQUEST';
export const MTDBOOKED_SUCCESS = 'MTDBOOKED_SUCCESS';
export const MTDBOOKED_FAILURE = 'MTDBOOKED_FAILURE';

export const MTDFINALIZED_STARTED = 'MTDFINALIZED_STARTED';
export const MTDFINALIZED_REQUEST = 'MTDFINALIZED_REQUEST';
export const MTDFINALIZED_SUCCESS = 'MTDFINALIZED_SUCCESS';
export const MTDFINALIZED_FAILURE = 'MTDFINALIZED_FAILURE';

export const STIPSNEEDED_STARTED = 'STIPSNEEDED_STARTED';
export const STIPSNEEDED_REQUEST = 'STIPSNEEDED_REQUEST';
export const STIPSNEEDED_SUCCESS = 'STIPSNEEDED_SUCCESS';
export const STIPSNEEDED_FAILURE = 'STIPSNEEDED_FAILURE';

export const UPDATESTIPSSTATUS_STARTED = 'UPDATESTIPSSTATUS_STARTED';
export const UPDATESTIPSSTATUS_REQUEST = 'UPDATESTIPSSTATUS_REQUEST';
export const UPDATESTIPSSTATUS_SUCCESS = 'UPDATESTIPSSTATUS_SUCCESS';
export const UPDATESTIPSSTATUS_FAILURE = 'UPDATESTIPSSTATUS_FAILURE';

export const MONTHLYLEADERBOARD_STARTED = 'MONTHLYLEADERBOARD_STARTED';
export const MONTHLYLEADERBOARD_REQUEST = 'MONTHLYLEADERBOARD_REQUEST';
export const MONTHLYLEADERBOARD_SUCCESS = 'MONTHLYLEADERBOARD_SUCCESS';
export const MONTHLYLEADERBOARD_FAILURE = 'MONTHLYLEADERBOARD_FAILURE';

export const MYSCHEDULE_STARTED = 'MYSCHEDULE_STARTED';
export const MYSCHEDULE_REQUEST = 'MYSCHEDULE_REQUEST';
export const MYSCHEDULE_SUCCESS = 'MYSCHEDULE_SUCCESS';
export const MYSCHEDULE_FAILURE = 'MYSCHEDULE_FAILURE';

export const COMPOSITESCORE_STARTED = 'COMPOSITESCORE_STARTED';
export const COMPOSITESCORE_REQUEST = 'COMPOSITESCORE_REQUEST';
export const COMPOSITESCORE_SUCCESS = 'COMPOSITESCORE_SUCCESS';
export const COMPOSITESCORE_FAILURE = 'COMPOSITESCORE_FAILURE';

export const COMPOSITELEADERBOARD_STARTED = 'COMPOSITELEADERBOARD_STARTED';
export const COMPOSITELEADERBOARD_REQUEST = 'COMPOSITELEADERBOARD_REQUEST';
export const COMPOSITELEADERBOARD_SUCCESS = 'COMPOSITELEADERBOARD_SUCCESS';
export const COMPOSITELEADERBOARD_FAILURE = 'COMPOSITELEADERBOARD_FAILURE';

export const CHANGEREQUEST_STARTED = 'CHANGEREQUEST_STARTED';
export const CHANGEREQUEST_REQUEST = 'CHANGEREQUEST_REQUEST';
export const CHANGEREQUEST_SUCCESS = 'CHANGEREQUEST_SUCCESS';
export const CHANGEREQUEST_FAILURE = 'CHANGEREQUEST_FAILURE';

export const DEALERSHIPSALES_STARTED = 'DEALERSHIPSALES_STARTED';
export const DEALERSHIPSALES_REQUEST = 'DEALERSHIPSALES_REQUEST';
export const DEALERSHIPSALES_SUCCESS = 'DEALERSHIPSALES_SUCCESS';
export const DEALERSHIPSALES_FAILURE = 'DEALERSHIPSALES_FAILURE';

export const MYSALES_STARTED = 'MYSALES_STARTED';
export const MYSALES_REQUEST = 'MYSALES_REQUEST';
export const MYSALES_SUCCESS = 'MYSALES_SUCCESS';
export const MYSALES_FAILURE = 'MYSALES_FAILURE';

export const TEAMLEADERBOARD_STARTED = 'TEAMLEADERBOARD_STARTED';
export const TEAMLEADERBOARD_REQUEST = 'TEAMLEADERBOARD_REQUEST';
export const TEAMLEADERBOARD_SUCCESS = 'TEAMLEADERBOARD_SUCCESS';
export const TEAMLEADERBOARD_FAILURE = 'TEAMLEADERBOARD_FAILURE';

export const DISPLAYTEAMEMPLOYEE_STARTED = 'DISPLAYTEAMEMPLOYEE_STARTED';
export const DISPLAYTEAMEMPLOYEE_REQUEST = 'DISPLAYTEAMEMPLOYEE_REQUEST';
export const DISPLAYTEAMEMPLOYEE_SUCCESS = 'DISPLAYTEAMEMPLOYEE_SUCCESS';
export const DISPLAYTEAMEMPLOYEE_FAILURE = 'DISPLAYTEAMEMPLOYEE_FAILURE';

export const YTDLEADERBOARD_STARTED = 'YTDLEADERBOARD_STARTED';
export const YTDLEADERBOARD_REQUEST = 'YTDLEADERBOARD_REQUEST';
export const YTDLEADERBOARD_SUCCESS = 'YTDLEADERBOARD_SUCCESS';
export const YTDLEADERBOARD_FAILURE = 'YTDLEADERBOARD_FAILURE';

export const CORPORATEUSERHOMEPAGE_STARTED = 'CORPORATEUSERHOMEPAGE_STARTED';
export const CORPORATEUSERHOMEPAGE_REQUEST = 'CORPORATEUSERHOMEPAGE_REQUEST';
export const CORPORATEUSERHOMEPAGE_SUCCESS = 'CORPORATEUSERHOMEPAGE_SUCCESS';
export const CORPORATEUSERHOMEPAGE_FAILURE = 'CORPORATEUSERHOMEPAGE_FAILURE';

export const CORPORATEMONTHLYLEADERBOARD_STARTED = 'CORPORATEMONTHLYLEADERBOARD_STARTED';
export const CORPORATEMONTHLYLEADERBOARD_REQUEST = 'CORPORATEMONTHLYLEADERBOARD_REQUEST';
export const CORPORATEMONTHLYLEADERBOARD_SUCCESS = 'CORPORATEMONTHLYLEADERBOARD_SUCCESS';
export const CORPORATEMONTHLYLEADERBOARD_FAILURE = 'CORPORATEMONTHLYLEADERBOARD_FAILURE';

export const SALESPERSONHOMEPAGE_STARTED = 'SALESPERSONHOMEPAGE_STARTED';
export const SALESPERSONHOMEPAGE_REQUEST = 'SALESPERSONHOMEPAGE_REQUEST';
export const SALESPERSONHOMEPAGE_SUCCESS = 'SALESPERSONHOMEPAGE_SUCCESS';
export const SALESPERSONHOMEPAGE_FAILURE = 'SALESPERSONHOMEPAGE_FAILURE';

export const SOURCETYPEGET_STARTED = 'SOURCETYPEGET_STARTED';
export const SOURCETYPEGET_REQUEST = 'SOURCETYPEGET_REQUEST';
export const SOURCETYPEGET_SUCCESS = 'SOURCETYPEGET_SUCCESS';
export const SOURCETYPEGET_FAILURE = 'SOURCETYPEGET_FAILURE';

export const CALENDERSCHEDULE_STARTED = 'CALENDERSCHEDULE_STARTED';
export const CALENDERSCHEDULE_REQUEST = 'CALENDERSCHEDULE_REQUEST';
export const CALENDERSCHEDULE_SUCCESS = 'CALENDERSCHEDULE_SUCCESS';
export const CALENDERSCHEDULE_FAILURE = 'CALENDERSCHEDULE_FAILURE';

export const USERTRACKING_STARTED = 'USERTRACKING_STARTED';
export const USERTRACKING_REQUEST = 'USERTRACKING_REQUEST';
export const USERTRACKING_SUCCESS = 'USERTRACKING_SUCCESS';
export const USERTRACKING_FAILURE = 'USERTRACKING_FAILURE';

export const CREATEGEOFENCE_STARTED = 'CREATEGEOFENCE_STARTED';
export const CREATEGEOFENCE_REQUEST = 'CREATEGEOFENCE_REQUEST';
export const CREATEGEOFENCE_SUCCESS = 'CREATEGEOFENCE_SUCCESS';
export const CREATEGEOFENCE_FAILURE = 'CREATEGEOFENCE_FAILURE';

export const USERSEARCH_STARTED = 'USERSEARCH_STARTED';
export const USERSEARCH_REQUEST = 'USERSEARCH_REQUEST';
export const USERSEARCH_SUCCESS = 'USERSEARCH_SUCCESS';
export const USERSEARCH_FAILURE = 'USERSEARCH_FAILURE';

export const UPBOARD_STARTED = 'UPBOARD_STARTED';
export const UPBOARD_REQUEST = 'UPBOARD_REQUEST';
export const UPBOARD_SUCCESS = 'UPBOARD_SUCCESS';
export const UPBOARD_FAILURE = 'UPBOARD_FAILURE';

export const UPDATE_UPBOARD_STARTED = 'UPDATE_UPBOARD_STARTED';
export const UPDATE_UPBOARD_REQUEST = 'UPDATE_UPBOARD_REQUEST';
export const UPDATE_UPBOARD_SUCCESS = 'UPDATE_UPBOARD_SUCCESS';
export const UPDATE_UPBOARD_FAILURE = 'UPDATE_UPBOARD_FAILURE';

export const UPBOARDNOTUP_STARTED = 'UPBOARDNOTUP_STARTED';
export const UPBOARDNOTUP_REQUEST = 'UPBOARDNOTUP_REQUEST';
export const UPBOARDNOTUP_SUCCESS = 'UPBOARDNOTUP_SUCCESS';
export const UPBOARDNOTUP_FAILURE = 'UPBOARDNOTUP_FAILURE';

export const NOTIFYUSER_STARTED = 'NOTIFYUSER_STARTED';
export const NOTIFYUSER_REQUEST = 'NOTIFYUSER_REQUEST';
export const NOTIFYUSER_SUCCESS = 'NOTIFYUSER_SUCCESS';
export const NOTIFYUSER_FAILURE = 'NOTIFYUSER_FAILURE';

export const SWITCHSHIFT_STARTED = 'SWITCHSHIFT_STARTED';
export const SWITCHSHIFT_REQUEST = 'SWITCHSHIFT_REQUEST';
export const SWITCHSHIFT_SUCCESS = 'SWITCHSHIFT_SUCCESS';
export const SWITCHSHIFT_FAILURE = 'SWITCHSHIFT_FAILURE';

export const SCHEDULECHANGE_STARTED = 'SCHEDULECHANGE_STARTED';
export const SCHEDULECHANGE_REQUEST = 'SCHEDULECHANGE_REQUEST';
export const SCHEDULECHANGE_SUCCESS = 'SCHEDULECHANGE_SUCCESS';
export const SCHEDULECHANGE_FAILURE = 'SCHEDULECHANGE_FAILURE';

export const SENDSWITCHNOTIFICATION_STARTED = 'SENDSWITCHNOTIFICATION_STARTED';
export const SENDSWITCHNOTIFICATION_REQUEST = 'SENDSWITCHNOTIFICATION_REQUEST';
export const SENDSWITCHNOTIFICATION_SUCCESS = 'SENDSWITCHNOTIFICATION_SUCCESS';
export const SENDSWITCHNOTIFICATION_FAILURE = 'SENDSWITCHNOTIFICATION_FAILURE';

export const NOTIFICATIONLIST_STARTED = 'NOTIFICATIONLIST_STARTED';
export const NOTIFICATIONLIST_REQUEST = 'NOTIFICATIONLIST_REQUEST';
export const NOTIFICATIONLIST_SUCCESS = 'NOTIFICATIONLIST_SUCCESS';
export const NOTIFICATIONLIST_FAILURE = 'NOTIFICATIONLIST_FAILURE';

export const ACTIVEGAMES_STARTED = 'ACTIVEGAMES_STARTED';
export const ACTIVEGAMES_REQUEST = 'ACTIVEGAMES_REQUEST';
export const ACTIVEGAMES_SUCCESS = 'ACTIVEGAMES_SUCCESS';
export const ACTIVEGAMES_FAILURE = 'ACTIVEGAMES_FAILURE';

export const TOTALSALESPERSON_STARTED = 'TOTALSALESPERSON_STARTED';
export const TOTALSALESPERSON_REQUEST = 'TOTALSALESPERSON_REQUEST';
export const TOTALSALESPERSON_SUCCESS = 'TOTALSALESPERSON_SUCCESS';
export const TOTALSALESPERSON_FAILURE = 'TOTALSALESPERSON_FAILURE';

export const MANAGEMENTNOTIFICATION_STARTED = 'MANAGEMENTNOTIFICATION_STARTED';
export const MANAGEMENTNOTIFICATION_REQUEST = 'MANAGEMENTNOTIFICATION_REQUEST';
export const MANAGEMENTNOTIFICATION_SUCCESS = 'MANAGEMENTNOTIFICATION_SUCCESS';
export const MANAGEMENTNOTIFICATION_FAILURE = 'MANAGEMENTNOTIFICATION_FAILURE';

export const GAMEPLAY_STARTED = 'GAMEPLAY_STARTED';
export const GAMEPLAY_REQUEST = 'GAMEPLAY_REQUEST';
export const GAMEPLAY_SUCCESS = 'GAMEPLAY_SUCCESS';
export const GAMEPLAY_FAILURE = 'GAMEPLAY_FAILURE';

export const GAMEPRIZE_STARTED = 'GAMEPRIZE_STARTED';
export const GAMEPRIZE_REQUEST = 'GAMEPRIZE_REQUEST';
export const GAMEPRIZE_SUCCESS = 'GAMEPRIZE_SUCCESS';
export const GAMEPRIZE_FAILURE = 'GAMEPRIZE_FAILURE';

export const GAMEWINNER_STARTED = 'GAMEWINNER_STARTED';
export const GAMEWINNER_REQUEST = 'GAMEWINNER_REQUEST';
export const GAMEWINNER_SUCCESS = 'GAMEWINNER_SUCCESS';
export const GAMEWINNER_FAILURE = 'GAMEWINNER_FAILURE';

export const REQUESTPTONOTIFICATION_STARTED = 'REQUESTPTONOTIFICATION_STARTED';
export const REQUESTPTONOTIFICATION_REQUEST = 'REQUESTPTONOTIFICATION_REQUEST';
export const REQUESTPTONOTIFICATION_SUCCESS = 'REQUESTPTONOTIFICATION_SUCCESS';
export const REQUESTPTONOTIFICATION_FAILURE = 'REQUESTPTONOTIFICATION_FAILURE';

export const CALLINSICKHRNOTIFICATION_STARTED = 'CALLINSICKHRNOTIFICATION_STARTED';
export const CALLINSICKHRNOTIFICATION_REQUEST = 'CALLINSICKHRNOTIFICATION_REQUEST';
export const CALLINSICKHRNOTIFICATION_SUCCESS = 'CALLINSICKHRNOTIFICATION_SUCCESS';
export const CALLINSICKHRNOTIFICATION_FAILURE = 'CALLINSICKHRNOTIFICATION_FAILURE';

export const COVERSHIFTNOTIFICATION_STARTED = 'COVERSHIFTNOTIFICATION_STARTED';
export const COVERSHIFTNOTIFICATION_REQUEST = 'COVERSHIFTNOTIFICATION_REQUEST';
export const COVERSHIFTNOTIFICATION_SUCCESS = 'COVERSHIFTNOTIFICATION_SUCCESS';
export const COVERSHIFTNOTIFICATION_FAILURE = 'COVERSHIFTNOTIFICATION_FAILURE';

export const PTOHRACTIONNOTIFICATION_STARTED = 'PTOHRACTIONNOTIFICATION_STARTED';
export const PTOHRACTIONNOTIFICATION_REQUEST = 'PTOHRACTIONNOTIFICATION_REQUEST';
export const PTOHRACTIONNOTIFICATION_SUCCESS = 'PTOHRACTIONNOTIFICATION_SUCCESS';
export const PTOHRACTIONNOTIFICATION_FAILURE = 'PTOHRACTIONNOTIFICATION_FAILURE';

export const PTOMANAGERACTIONNOTIFICATION_STARTED = 'PTOMANAGERACTIONNOTIFICATION_STARTED';
export const PTOMANAGERACTIONNOTIFICATION_REQUEST = 'PTOMANAGERACTIONNOTIFICATION_REQUEST';
export const PTOMANAGERACTIONNOTIFICATION_SUCCESS = 'PTOMANAGERACTIONNOTIFICATION_SUCCESS';
export const PTOMANAGERACTIONNOTIFICATION_FAILURE = 'PTOMANAGERACTIONNOTIFICATION_FAILURE';

export const CALLINSICKHRACTIONNOTIFICATION_STARTED = 'CALLINSICKHRACTIONNOTIFICATION_STARTED';
export const CALLINSICKHRACTIONNOTIFICATION_REQUEST = 'CALLINSICKHRACTIONNOTIFICATION_REQUEST';
export const CALLINSICKHRACTIONNOTIFICATION_SUCCESS = 'CALLINSICKHRACTIONNOTIFICATION_SUCCESS';
export const CALLINSICKHRACTIONNOTIFICATION_FAILURE = 'CALLINSICKHRACTIONNOTIFICATION_FAILURE';

export const MANAGERACTIONCALLINSICK_STARTED = 'MANAGERACTIONCALLINSICK_STARTED';
export const MANAGERACTIONCALLINSICK_REQUEST = 'MANAGERACTIONCALLINSICK_REQUEST';
export const MANAGERACTIONCALLINSICK_SUCCESS = 'MANAGERACTIONCALLINSICK_SUCCESS';
export const MANAGERACTIONCALLINSICK_FAILURE = 'MANAGERACTIONCALLINSICK_FAILURE';

export const SENDRUNNINGLATENOTIFICATION_STARTED = 'SENDRUNNINGLATENOTIFICATION_STARTED';
export const SENDRUNNINGLATENOTIFICATION_REQUEST = 'SENDRUNNINGLATENOTIFICATION_REQUEST';
export const SENDRUNNINGLATENOTIFICATION_SUCCESS = 'SENDRUNNINGLATENOTIFICATION_SUCCESS';
export const SENDRUNNINGLATENOTIFICATION_FAILURE = 'SENDRUNNINGLATENOTIFICATION_FAILURE';

export const SWITCHSHIFTSTATUSSALESPERSON_STARTED = 'SWITCHSHIFTSTATUSSALESPERSON_STARTED';
export const SWITCHSHIFTSTATUSSALESPERSON_REQUEST = 'SWITCHSHIFTSTATUSSALESPERSON_REQUEST';
export const SWITCHSHIFTSTATUSSALESPERSON_SUCCESS = 'SWITCHSHIFTSTATUSSALESPERSON_SUCCESS';
export const SWITCHSHIFTSTATUSSALESPERSON_FAILURE = 'SWITCHSHIFTSTATUSSALESPERSON_FAILURE';

export const MGRSTATUSFORSWITCHSHIFT_STARTED = 'MGRSTATUSFORSWITCHSHIFT_STARTED';
export const MGRSTATUSFORSWITCHSHIFT_REQUEST = 'MGRSTATUSFORSWITCHSHIFT_REQUEST';
export const MGRSTATUSFORSWITCHSHIFT_SUCCESS = 'MGRSTATUSFORSWITCHSHIFT_SUCCESS';
export const MGRSTATUSFORSWITCHSHIFT_FAILURE = 'MGRSTATUSFORSWITCHSHIFT_FAILURE';

export const SHIFTCVRGREQUSTTOSALESPERSON_STARTED = 'SHIFTCVRGREQUSTTOSALESPERSON_STARTED';
export const SHIFTCVRGREQUSTTOSALESPERSON_REQUEST = 'SHIFTCVRGREQUSTTOSALESPERSON_REQUEST';
export const SHIFTCVRGREQUSTTOSALESPERSON_SUCCESS = 'SHIFTCVRGREQUSTTOSALESPERSON_SUCCESS';
export const SHIFTCVRGREQUSTTOSALESPERSON_FAILURE = 'SHIFTCVRGREQUSTTOSALESPERSON_FAILURE';

export const SHIFTCVRGSTATUSSALESPERSON_STARTED = 'SHIFTCVRGSTATUSSALESPERSON_STARTED';
export const SHIFTCVRGSTATUSSALESPERSON_REQUEST = 'SHIFTCVRGSTATUSSALESPERSON_REQUEST';
export const SHIFTCVRGSTATUSSALESPERSON_SUCCESS = 'SHIFTCVRGSTATUSSALESPERSON_SUCCESS';
export const SHIFTCVRGSTATUSSALESPERSON_FAILURE = 'SHIFTCVRGSTATUSSALESPERSON_FAILURE';

export const MGRSTATUSFORSHIFTCVRGE_STARTED = 'MGRSTATUSFORSHIFTCVRGE_STARTED';
export const MGRSTATUSFORSHIFTCVRGE_REQUEST = 'MGRSTATUSFORSHIFTCVRGE_REQUEST';
export const MGRSTATUSFORSHIFTCVRGE_SUCCESS = 'MGRSTATUSFORSHIFTCVRGE_SUCCESS';
export const MGRSTATUSFORSHIFTCVRGE_FAILURE = 'MGRSTATUSFORSHIFTCVRGE_FAILURE';

export const RUNINGLATENOTIFICATIONACTIONBYMANAGER_STARTED = 'RUNINGLATENOTIFICATIONACTIONBYMANAGER_STARTED';
export const RUNINGLATENOTIFICATIONACTIONBYMANAGER_REQUEST = 'RUNINGLATENOTIFICATIONACTIONBYMANAGER_REQUEST';
export const RUNINGLATENOTIFICATIONACTIONBYMANAGER_SUCCESS = 'RUNINGLATENOTIFICATIONACTIONBYMANAGER_SUCCESS';
export const RUNINGLATENOTIFICATIONACTIONBYMANAGER_FAILURE = 'RUNINGLATENOTIFICATIONACTIONBYMANAGER_FAILURE';

export const MANAGEMENTNTFCTIONACKLDGE_STARTED = 'MANAGEMENTNTFCTIONACKLDGE_STARTED';
export const MANAGEMENTNTFCTIONACKLDGE_REQUEST = 'MANAGEMENTNTFCTIONACKLDGE_REQUEST';
export const MANAGEMENTNTFCTIONACKLDGE_SUCCESS = 'MANAGEMENTNTFCTIONACKLDGE_SUCCESS';
export const MANAGEMENTNTFCTIONACKLDGE_FAILURE = 'MANAGEMENTNTFCTIONACKLDGE_FAILURE';

export const SENDVCARD_STARTED = 'SENDVCARD_STARTED';
export const SENDVCARD_REQUEST = 'SENDVCARD_REQUEST';
export const SENDVCARD_SUCCESS = 'SENDVCARD_SUCCESS';
export const SENDVCARD_FAILURE = 'SENDVCARD_FAILURE';

export const COMPOSITELEADERBOARDYTD_STARTED = 'COMPOSITELEADERBOARDYTD_STARTED';
export const COMPOSITELEADERBOARDYTD_REQUEST = 'COMPOSITELEADERBOARDYTD_REQUEST';
export const COMPOSITELEADERBOARDYTD_SUCCESS = 'COMPOSITELEADERBOARDYTD_SUCCESS';
export const COMPOSITELEADERBOARDYTD_FAILURE = 'COMPOSITELEADERBOARDYTD_FAILURE';

export const TERMSNCONDITIONEMAIL_STARTED = 'TERMSNCONDITIONEMAIL_STARTED';
export const TERMSNCONDITIONEMAIL_REQUEST = 'TERMSNCONDITIONEMAIL_REQUEST';
export const TERMSNCONDITIONEMAIL_SUCCESS = 'TERMSNCONDITIONEMAIL_SUCCESS';
export const TERMSNCONDITIONEMAIL_FAILURE = 'TERMSNCONDITIONEMAIL_FAILURE';


export const YTDTEAMLEADERBOARD_STARTED = 'YTDTEAMLEADERBOARD_STARTED';
export const YTDTEAMLEADERBOARD_REQUEST = 'YTDTEAMLEADERBOARD_REQUEST';
export const YTDTEAMLEADERBOARD_SUCCESS = 'YTDTEAMLEADERBOARD_SUCCESS';
export const YTDTEAMLEADERBOARD_FAILURE = 'YTDTEAMLEADERBOARD_FAILURE';

export const SENDMESSAGE_STARTED = 'SENDMESSAGE_STARTED';
export const SENDMESSAGE_REQUEST = 'SENDMESSAGE_REQUEST';
export const SENDMESSAGE_SUCCESS = 'SENDMESSAGE_SUCCESS';
export const SENDMESSAGE_FAILURE = 'SENDMESSAGE_FAILURE';

export const GETMESSAGE_STARTED = 'GETMESSAGE_STARTED';
export const GETMESSAGE_REQUEST = 'GETMESSAGE_REQUEST';
export const GETMESSAGE_SUCCESS = 'GETMESSAGE_SUCCESS';
export const GETMESSAGE_FAILURE = 'GETMESSAGE_FAILURE';

export const LOGOUTURL_STARTED = 'LOGOUTURL_STARTED';
export const LOGOUTURL_REQUEST = 'LOGOUTURL_REQUEST';
export const LOGOUTURL_SUCCESS = 'LOGOUTURL_SUCCESS';
export const LOGOUTURL_FAILURE = 'LOGOUTURL_FAILURE';


export const SOSNOTIFICATION_REQUEST = 'SOSNOTIFICATION_REQUEST';
export const SOSNOTIFICATION_SUCCESS = 'SOSNOTIFICATION_SUCCESS';
export const SOSNOTIFICATION_STARTED = 'SOSNOTIFICATION_STARTED';
export const SOSNOTIFICATION_FAILURE = 'SOSNOTIFICATION_FAILURE';

export const YTDCOMPOSITESCORE_REQUEST = 'YTDCOMPOSITESCORE_REQUEST';
export const YTDCOMPOSITESCORE_SUCCESS = 'YTDCOMPOSITESCORE_SUCCESS';
export const YTDCOMPOSITESCORE_STARTED = 'YTDCOMPOSITESCORE_STARTED';
export const YTDCOMPOSITESCORE_FAILURE = 'YTDCOMPOSITESCORE_FAILURE';

export const CHANGEPASSWORD_REQUEST = 'CHANGEPASSWORD_REQUEST';
export const CHANGEPASSWORD_SUCCESS = 'CHANGEPASSWORD_SUCCESS';
export const CHANGEPASSWORD_STARTED = 'CHANGEPASSWORD_STARTED';
export const CHANGEPASSWORD_FAILURE = 'CHANGEPASSWORD_FAILURE';

export const NOTIFICATIONHISTORY_REQUEST = 'NOTIFICATIONHISTORY_REQUEST';
export const NOTIFICATIONHISTORY_SUCCESS = 'NOTIFICATIONHISTORY_SUCCESS';
export const NOTIFICATIONHISTORY_STARTED = 'NOTIFICATIONHISTORY_STARTED';
export const NOTIFICATIONHISTORY_FAILURE = 'NOTIFICATIONHISTORY_FAILURE';

export const SUPPORT_REQUEST = 'SUPPORT_REQUEST';
export const SUPPORT_SUCCESS = 'SUPPORT_SUCCESS';
export const SUPPORT_STARTED = 'SUPPORT_STARTED';
export const SUPPORT_FAILURE = 'SUPPORT_FAILURE';

export const MANAGEMENTNOTIFICATIONLIST_REQUEST = 'MANAGEMENTNOTIFICATIONLIST_REQUEST';
export const MANAGEMENTNOTIFICATIONLIST_SUCCESS = 'MANAGEMENTNOTIFICATIONLIST_SUCCESS';
export const MANAGEMENTNOTIFICATIONLIST_STARTED = 'MANAGEMENTNOTIFICATIONLIST_STARTED';
export const MANAGEMENTNOTIFICATIONLIST_FAILURE = 'MANAGEMENTNOTIFICATIONLIST_FAILURE';

export const MANAGERGAMESDETAILS_REQUEST = 'MANAGERGAMESDETAILS_REQUEST';
export const MANAGERGAMESDETAILS_SUCCESS = 'MANAGERGAMESDETAILS_SUCCESS';
export const MANAGERGAMESDETAILS_STARTED = 'MANAGERGAMESDETAILS_STARTED';
export const MANAGERGAMESDETAILS_FAILURE = 'MANAGERGAMESDETAILS_FAILURE';

export const ORDERDETAILS_REQUEST = 'ORDERDETAILS_REQUEST';
export const ORDERDETAILS_SUCCESS = 'ORDERDETAILS_SUCCESS';
export const ORDERDETAILS_STARTED = 'ORDERDETAILS_STARTED';
export const ORDERDETAILS_FAILURE = 'ORDERDETAILS_FAILURE';

export const ORDERUPDATE_REQUEST = 'ORDERUPDATE_REQUEST';
export const ORDERUPDATE_SUCCESS = 'ORDERUPDATE_SUCCESS';
export const ORDERUPDATE_STARTED = 'ORDERUPDATE_STARTED';
export const ORDERUPDATE_FAILURE = 'ORDERUPDATE_FAILURE';
